### ISSUE TITLE
Headings usable in the vault

### ISSUE THREAD

**Issue by Andrea-28-03** [maradotwebp/obsidian-avatar#3]
When I put an Header in an avatar code block it render it, but i doesn’t see it on the [floating-toc-plugin](https://github.com/PKM-er/obsidian-floating-toc-plugin) or when i try to link to it.
![image](https://github.com/froehlichA/obsidian-avatar/assets/62112468/cdd28436-ea2e-4d8d-9387-4b12b721d2ee)
![image](https://github.com/froehlichA/obsidian-avatar/assets/62112468/0cc95364-cfae-48e5-b418-bb7282b1e9a0)

Is there a way with snippets or writing something on the theme to remove the restriction in this codeblock?
Or some other way to make it possible?

**Comment by maradotwebp** [comment]
I can render the markdown in the description, but Obsidian doesn't consider it to be part of the active document. As far as I know, this is a limitation by Obsidian and I can't circumvent it directly.

Various other plugins like [multi-column-markdown](https://github.com/ckRobinson/multi-column-markdown) use "hacks" by requiring you to put your content outside the codeblock and adding special `--- end-column ---` lines, like so:
````
```start-multi-column
ID: ExampleRegion1
number of columns: 2
largest column: left
```

Text displayed in column 1.

--- end-column ---

Text displayed in column 2.

--- end-multi-column
````

Unfortunately, this would both require a rewrite that will complicate this plugin enormously, and also break it for existing users.

I would be happy to be proven wrong though! If you know of any plugin where you can write markdown in a codeblock and still have headings in there rendered in your TOC plugin, send me a link to their github repository and I'll take a look at it.

**Comment by Andrea-28-03** [comment]
Ok thanks anyways, if i find something i will put it here
